version: "2.1"

services:
  nfs:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - "nfs:/nfs"
    cap_add:
      - SYS_ADMIN
    environment:
      # Decide if you want the NFS container to auto sync the content of the `share` folder. True or False.
      SYNC: True
      # Be warned, this provides complete root access to the volume to clients. Reconfigure all_squash,
      # insecure, anonuid and anongid to be more secure: https://linux.die.net/man/5/exports
      NFS_EXPORT_0: "/nfs *(rw,sync,no_subtree_check,no_auth_nlm,insecure,all_squash,anonuid=0,anongid=0,fsid=root)"
    restart: always

    # If you would like to share the NFS volume with another container, ensure the other container
    # `depends_on` the NFS container by including the below in your other container:
    # depends_on:
    #  - nfs

volumes:
  nfs:
